trigger:
  branches:
    include:
      - uat-branch

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  # Create this as a secret variable in Azure DevOps
  azureStaticWebAppsApiToken: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

steps:
- checkout: self
  submodules: true
  lfs: false

- task: AzureStaticWebApp@0
  displayName: Build and Deploy Static Web App
  inputs:
    app_location: "src"
    api_location: "api"
    output_location: "src"
    azure_static_web_apps_api_token: $(azureStaticWebAppsApiToken)
    deployment_environment: "uatrelease"
